apiVersion: apps/v1
kind: Deployment
metadata: 
  name: qr-dp
  namespace: qr-code
  labels:
    app: qr-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-be
  template:
    metadata:
      labels:
        app: qr-be
    spec:
      containers:
      - name: qr-backend
        image: dhruvpatil56/qr-backend:latest
        ports:
          - containerPort: 3000
 
