apiVersion: v1
kind: Service
metadata:
  name: qr-svc-fe
  namespace: qr-code
spec:
  type: ClusterIP
  selector:
    app: qr-fe
  ports:
    - protocol : TCP
      targetPort: 3000
      port: 3000
      name: tcp-fe  
