name: QR Code CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: dhruvpatil56

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------- SonarQube Static Analysis ----------
      - name: Set up SonarQube Scanner
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Run SonarQube Analysis
        run: sonar-scanner
        working-directory: ./api

      # ---------- Trivy Security Scan ----------
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy -y

      - name: Run Trivy Filesystem Scan
        run: trivy fs . --exit-code 0 --format table --output trivy-report.txt

      # ---------- Docker Build & Push ----------
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build and Push Backend Docker Image
        run: |
          docker build -f api/Dockerfile -t $DOCKERHUB_USERNAME/qr-backend:latest ./api
          docker push $DOCKERHUB_USERNAME/qr-backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -f front-end-nextjs/Dockerfile -t $DOCKERHUB_USERNAME/qr-frontend:latest ./front-end-nextjs
          docker push $DOCKERHUB_USERNAME/qr-frontend:latest

      # ---------- Local Container Run (Optional for Dev only) ----------
      - name: Stop Existing Containers (Dev Only)
        if: false
        run: |
          docker rm -f qr-backend || true
          docker rm -f qr-frontend || true

      - name: Run Backend Locally (Dev Only)
        if: false
        run: docker run -d --name qr-backend -p 8000:8000 $DOCKERHUB_USERNAME/qr-backend:latest

      - name: Run Frontend Locally (Dev Only)
        if: false
        run: docker run -d --name qr-frontend -p 3000:3000 $DOCKERHUB_USERNAME/qr-frontend:latest
